// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dngdcuixtfihfvdxdyzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuZ2RjdWl4dGZpaGZ2ZHhkeXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjU3ODcsImV4cCI6MjA2MjgwMTc4N30.MNP6ADMMchrmK6ubq-4pbqt21peloyaCb-ov3mLDSbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});